<!DOCTYPE HTML>
<php lang="en-US">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" content="Crozeal, Image Procesing, Data Analytics, Digitzing Goverment, PMFBY Portal, Farmer Digitzation, Information Asymmetry, Agri techies, Crop Insurance, Agriculture Farming, industrial Agriculture, industrial Agriculture, Jamabandi, Girdawari, Patwari, Pradhan Mantri Fasal Bima Yojana, Kisan Credit Card, E Mitra, Digital Agriculture, Research Agriculture, Agriculture Development, Community Agriculture, Agriculture Tractors, Machine Learning" />
<meta name="description" content="Digitizing agricultural assessment techniques r using data analytics" />
        <title>Crozeal-Delivering Technology With Zeal</title>
        <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-85350603-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-85350603-3');
</script>

        <link rel="shortcut icon" type="image/x-icon" href="favicon.png" />

        <link href="css/master.css" rel="stylesheet">

        <!-- SWITCHER -->
        <link rel="stylesheet" id="switcher-css" type="text/css" href="plugins/switcher/css/switcher.css" media="all" />
        <link rel="alternate stylesheet" type="text/css" href="plugins/switcher/css/color1.css" title="color1" media="all" />
        <link rel="alternate stylesheet" type="text/css" href="plugins/switcher/css/color2.css" title="color2" media="all" />
        <link rel="alternate stylesheet" type="text/css" href="plugins/switcher/css/color3.css" title="color3" media="all" />
        <link rel="alternate stylesheet" type="text/css" href="plugins/switcher/css/color4.css" title="color4" media="all" />

        <script src="js/jquery-1.11.2.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/websitehelper.js" type="text/javascript"></script>
        <script src="js/webconstant.js" type="text/javascript"></script>


    </head>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "crozeal",
  "logo" : "http://crozeal.com/img/crozeal_logo.png",
  "image" : "http://crozeal.com/img/crozeal_logo.png",
  "address" : "Greater Noida",
  "priceRange" : "0-10000",
  "telephone" : "+91 120 416 3900",
  "url" : "http://crozeal.com/index.php",
   "sameAs": [
    "https://www.facebook.com/Crozeal-1547673565358465/"
    ]
}
</script>
    <body data-scrolling-animations="true">
        <div class="b-page">
            <!-- Start Switcher -->
<!--            <div class="switcher-wrapper">
                <div class="demo_changer">
                    <div class="demo-icon customBgColor"><span class="ef icon_cog "></span></div>
                    <div class="form_holder">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="predefined_styles">
                                    <div class="skin-theme-switcher">
                                        <h4>Skin</h4>
                                        <a href="#" data-switchcolor="color1" class="styleswitch" style="background-color:#7da500;"> </a>
                                        <a href="#" data-switchcolor="color2" class="styleswitch" style="background-color:#b7ca0d;"> </a>
                                        <a href="#" data-switchcolor="color3" class="styleswitch" style="background-color:#0bdabc;"> </a>
                                        <a href="#" data-switchcolor="color4" class="styleswitch" style="background-color:#01a664;"> </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>-->
            <!-- End Switcher -->
            <header id="header" class="header-3">
                <div class="header-top">
                    <div class="wrapper">
                        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <div class="header-info">
                                <div class="description-header">
                                    Welcome to CroZeal. Agriculture Services
                                </div>
                                <div class="color-primary">
                                    +91 120 416 3900                                </div>
                                <div class="color-primary">
                                    crozeal.com
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                            <ul class="cont-share pull-right">
                                <li><span class="share-icon"><span class="ef social_facebook_square "></span></span></li>
                                <li><span class="share-icon"><span class="ef social_twitter_square "></span></span></li>
                                <li><span class="share-icon"><span class="ef social_pinterest_square "></span></span></li>
                                <li><span class="share-icon"><span class="ef social_youtube_square "></span></span></li>
                                <li><span class="share-icon"><span class="ef social_instagram_square "></span></span></li>
                                <li><span class="share-icon"><span class="ef social_googleplus_square "></span></span></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="header-nav">
                    <div class="wrapper">
                        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6" style="margin-top: -18px; ">
                            <a href="index.php" class="logo" style="position: absolute; width: 100px; height: 100px; background-repeat: no-repeat;"></a>
                        </div>

                        <div class="col-lg-2 col-md-2 col-sm-3 col-xs-6 cart-block-r">
                            <div class="cart-block pull-right">
                                <!-- <a href="#" class="h-button text-uppercase pull-right"> -->
                                        <!-- <span class="cont-btn">
                                                <span class="ef icon_documents"></span>
                                                <span class="text-btn">Get Free Quote</span>
                                        </span> -->
                                </a>
                            </div>
                        </div>

                        <div class="col-lg-8 col-md-8 col-sm-7 col-xs-12 nav-box">
                            <span id="toggle-nav" class="ef icon_menu mobile-menu-toggle"></span>
                            <nav class="nav-container">
                                <ul>
                                    <li class="search pull-right">
                                        <form class="search-form form-inline" action="#" method="POST">
                                            <div class="form-group">
                                                <label class="sr-only" for="searchQuery">Search...</label>
                                                <input type="search" class="search-field" id="searchQuery" placeholder="Search...">
                                            </div>
                                            <button type="submit" class="hidden"><span class="ef icon_search"></span></button>
                                        </form>
                                        <a class="iconSearch" href="#">
                                            <span class="ef icon_search"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="#" href="index.php">Home</a>
                                        <!--<ul class="submenu">
                                                <li>
                                                        <a class="#" href="index.php">Home 1</a>
                                                </li>
                                                <li>
                                                        <a class="#" href="index.php">Home 2</a>
                                                </li>
                                        </ul>-->
                                    </li>
                                    <li><a class="#" href="about.php">About</a></li>
                                    <li><a class="#" href="#">Services</a></li>
                                    <li><a class="#" href="product_thumbnail_list.php">Store</a></li>
                                    <li><a class="#" href="index.php">Blog</a></li>
                                    <li><a class="#" href="contact.php">Contact</a></li>

                                </ul>
                            </nav>
                        </div>

                    </div>
                </div>
            </header>
